### ISSUE TITLE
Slow down hover State annotation for links

### ISSUE THREAD

**Issue by gndclouds** [gndclouds/11-11#1]

**Comment by jaeminkim-ISC** [comment]
To change the speed of the hover state annotation for links:

/assets/main.scss

a::after {
  position: absolute;
  left: 0;
  content: '';
  width: 100%;
  height: 2px;
  background: #ff0dbf;
  bottom: 5px;
  transform: scale(0, 2);
   transition: transform 1s;
  transform-origin: left top;
}

Change the transition time argument.
