### ISSUE TITLE
Jennifer Firestone, Selections from Ten

### ISSUE THREAD

**Issue by gndclouds** [gndclouds/11-11#10]
- [x] title should read: Selections from Ten
- [x] visual hierarchy of title/name feels inverted; Let's have the title of the work bold/large at the top, and the title of the author below, smaller, but still set apart visually from body copy
- [x] line breaks are off; line breaks should exactly match what is shown in the PDF
- [x] in the poem that begins "They ask if I’ll put them in the ground" line leading is off; all lines should be vertically spaced consistently

**Comment by weiweihsu** [comment]
edited bullet one
