### ISSUE TITLE
Mobile Layout

### ISSUE THREAD

**Issue by gndclouds** [gndclouds/11-11#10]
the layout, particularly on the landing page, appears to only work at a very large viewport. The site should be as mobile friendly as possible. (In the last four months, over 40 percent of our external traffic to cca.edu was mobile.)

**Comment by jaeminkim-ISC** [comment]
The scripts in the scripts.html look like a good place to start.

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

**Comment by jaeminkim-ISC** [comment]
Simple solution of changing the font size from pixels to em solved the main issue with mobile layout.

**Comment by jaeminkim-ISC** [comment]
Also moved away from the home page being a horizontal scroll-able page to a vertical scroll-able page.
