### ISSUE TITLE
 May-lee Chai, White Rabbits

### ISSUE THREAD

**Issue by gndclouds** [gndclouds/11-11#11]
- [x] the formatting of this piece looks different from Jennifer Firestone's.... I believe all pieces should have the same formatting, and I personally prefer the version shown for Jennifer (no blue bar, title and author name flush left at top).
- [x] font of body copy also looks different from Jennifer's. All text in all pieces should be in the same font.
- [x] can margins be widened so the text doesn't run as far to the edge? I think we should establish a consistent "page width" for all work to sit within. Can you adjust all so there is generous white space on the right and left of each work?
- [x] let's remove indents on new paragraphs. I like the formatting of Lorelei Lee's "Leaving San Francisco." New paragraphs are set apart by line breaks, not indents.
- [x]  in the sentence that begins "Still he pulled me along side him," please make alongside one word

**Comment by weiweihsu** [comment]
edits made for the 4th and 5th bullet points
