### ISSUE TITLE
Lorelei Lee, Leaving San Francisco

### ISSUE THREAD

**Issue by gndclouds** [gndclouds/11-11#13]
- [x] this piece is by Lorelei Lee, not May-lee Chai.
- [x] style author name / title as described above
- [x] remove "2015"
- [x] I like this formatting; the font, line leading, and margins all look good. Can this be replicated for all pieces please?
- [x] in the sentence, "She wrote, _I will always remember_", remove underscores and italicize I will always remember.
- [x] several sentences with em dashes need the spaces around the dashes removed:

    • "I ate foods I’d never heard of in restaurants with men who worked there as waiters — crepes, shiso, fermented bean sauce, something lit on fire beside the table"
    • "I told her what I was doing for money – that I had answered some ads," (in this one, there is an en dash where there should be an em dash —
    • "the men who owned new digital cameras snapped the shutter that was no longer an actual shutter — the click, click, click, click only a"
    • "They were named Cybernet Entertainment – a beginning-of-the-internet name – and they were housed"
    • "It was a thing that still seemed possible then — keeping secrets."
    • "When I learned the words “queer femme” — learned that there were names"
    • "watery-grey stains covered our walls and the apartment above us was a black shell, but everything else — one hundred books — had been saved."
    • "We’d end up at the Lexington Club – the Lex – packed into a hot crowd of queers." also, make sure those are em dashes
    • "This tableau – of curves and heels onto which you could project any dream, the dream of imaginary creatures who might live always naked and soft and waiting for you in a carpeted box — lasted less than a second before the woman nearest me transformed into someone specific." also, make sure those are em dashes
    • "The Lexington closed this year – their customers displaced in the tech-crowded Mission District – and there is no longer a lesbian bar in San Francisco. " also, make sure those are em dashes
    • "The people who can afford to drink those cocktails will play at something — edginess? danger? sex? — in a room that has been sanitized and remade as an imagined version of what it used to be."
    • "They want the actual dangers of our lives — the stigma and risk of violence that come with being poor and working naked — to be a thing they can purchase for an hour and then shake off, a thing that never sticks."
    • "Francesca and I did many things together — some of them drugs, some of them ugly. For a time, there was nothing I did without thinking of her. For a time, everything we did was together. I always thought that of the two of us, she was the one — the smart one, the one with talent and daring."
    • "Every day that I walk up 14th Street — one hundred times, two hundred times after her death — my chest goes hot and big and tight. I have the impulse to burn something — anything, everything — to build an alter of fire in front of the apartment where we lived."
    • "Hard not to feel like there is space for them everywhere — white and young and educated and bright as they are — and no place, again, for people like me."

- [x] remove underscores: "walked past children and couples and old men sweeping their shop-fronts_._ "
- [x]  in the sentence, "Golden Gate Park broke in front of me, the rose garden wide and thorned, secreted behind a wall of trees, bare of roses in November and suddenly hushed after the rushing traffic." I believe secreted should just read secret
- [x]  in the sentence "It was 2001 when I moved out of the house on 11thAvenue" there should be a space between 11th and Avenue
- [x] in the sentence "The ads were in the back pages of the Weekly and the Guardian," italicize Weekly and Guardian
- [x] in the sentence "_Models wanted: 18 and over. Must be height-weight proportional. Make up to $1000 a day. No experience necessary._" remove underscores and italicize: "Models wanted: 18 and over. Must be height-weight proportional. Make up to $1000 a day. No experience necessary."
- [x] there's a line/paragraph break here that shouldn't be: "Ashley would lean into the bar and order us drinks. One night, she shouted to the bartender, “My girlfriend’s a porn star."
- [x] in the sentence "I walk up Fourteenth Street" change Fourteenth to 14th
- [x] remove hyphen in "Chinese-American" to read "Chinese American"

**Comment by weiweihsu** [comment]
everything but bullet one is edited
check italics
